# Generated by Django 3.2.16 on 2023-02-24 11:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('Asosiy', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Statistika',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('miqdor', models.PositiveIntegerField()),
                ('sana', models.DateTimeField()),
                ('umumiy_suma', models.PositiveBigIntegerField()),
                ('tolandi', models.PositiveBigIntegerField()),
                ('nasiya', models.PositiveBigIntegerField()),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Asosiy.client')),
                ('mahsulot', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Asosiy.mahsulot')),
            ],
        ),
    ]
